backend:
  name: github
  repo: Jirka1969/truhlarstvivanha-site
  branch: main
  base_url: https://truhlarstvivanha-site-mtn1zr8pb-jiri-vanhas-projects.vercel.app
  auth_endpoint: /admin/auth.html
  client_id: Ov23lir5cQHPK667kcJW

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://truhlarstvivanha-site-mtn1zr8pb-jiri-vanhas-projects.vercel.app"

collections:
  - name: "stranky"
    label: "Stránky"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
