backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://truhlarstvivanha.netlify.app"

collections:
  - name: "stranky"
    label: "Stránky"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
